#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../config/boot"
require "local_ci_plus"
require "active_support/continuous_integration"

CI = ActiveSupport::ContinuousIntegration
require_relative "../config/ci"
